### ISSUE TITLE
Light distance no longer configurable in blender 2.8x+

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-blender#11]
We may need something like this:
```
# .distance property in blender 2.8+ is no longer configurable in GUI, we use the "Radius" now
# which is .shadow_soft_size in API
instancing = []
for object in bpy.context.scene.objects:
    if object.type=="LIGHT" and object["type"].upper() == "LIGHT" and not object.data.name in instancing:
        object.data.energy = object.data.energy / 100.0
        object.data.shadow_soft_size = object.data.distance
        instancing.append(object.data.name)
```

"Radius" in blender 2.8x is .object.data.shadow_soft_size, so we need to use it instead of .distance

blender expert is it correct? ![](https://cdn.lihkg.com/assets/faces/cow/sorry.gif)

**Comment by Benau** [comment]
no reply! https://github.com/supertuxkart/stk-blender/commit/592cd67bedd0d73b69cecee5fc4e6a27d892057a ![](https://cdn.lihkg.com/assets/faces/cow/bus_special.gif)![](https://cdn.lihkg.com/assets/faces/cow/bus_special.gif)![](https://cdn.lihkg.com/assets/faces/cow/bus_special.gif)![](https://cdn.lihkg.com/assets/faces/cow/bus_special.gif)![](https://cdn.lihkg.com/assets/faces/cow/bus_special.gif)![](https://cdn.lihkg.com/assets/faces/cow/bus_special.gif)

**Comment by RQWorldblender** [comment]
> no reply! [592cd67](https://github.com/supertuxkart/stk-blender/commit/592cd67bedd0d73b69cecee5fc4e6a27d892057a) ![](https://camo.githubusercontent.com/05ec40a3957d4f43d18eabb44d9e010b78b8a2891e3f3d738e2e01761b509669/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f636f772f6275735f7370656369616c2e676966)![](https://camo.githubusercontent.com/05ec40a3957d4f43d18eabb44d9e010b78b8a2891e3f3d738e2e01761b509669/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f636f772f6275735f7370656369616c2e676966)![](https://camo.githubusercontent.com/05ec40a3957d4f43d18eabb44d9e010b78b8a2891e3f3d738e2e01761b509669/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f636f772f6275735f7370656369616c2e676966)![](https://camo.githubusercontent.com/05ec40a3957d4f43d18eabb44d9e010b78b8a2891e3f3d738e2e01761b509669/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f636f772f6275735f7370656369616c2e676966)![](https://camo.githubusercontent.com/05ec40a3957d4f43d18eabb44d9e010b78b8a2891e3f3d738e2e01761b509669/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f636f772f6275735f7370656369616c2e676966)![](https://camo.githubusercontent.com/05ec40a3957d4f43d18eabb44d9e010b78b8a2891e3f3d738e2e01761b509669/68747470733a2f2f63646e2e6c69686b672e636f6d2f6173736574732f66616365732f636f772f6275735f7370656369616c2e676966)

Sorry that I wasn't able to come. From all that I saw for that issue, it should be correct, though I haven't tested it.
Actually I can't be considered a Blender expert, because I haven't fully explored everything that Blender offers, since most of it is useless for STK.
