### ISSUE TITLE
No exporter shows up

### ISSUE THREAD

**Issue by SlackySlackereon** [supertuxkart/stk-blender#2]
Hello, I was trying to mod my SuperTuxKart v1.2 installation to look like a mix of various old SuperTuxKart versions. When I try to export an old SuperTuxKart v0.7.0 model into an SPM, clicking on File > Export doesn't show it.

**Comment by Benau** [comment]
You cannot import b3d model from 0.7.0...

**Comment by SlackySlackereon** [comment]
Whoops. I'm repairing this issue. My brain broke.

**Comment by Benau** [comment]
![](https://cdn.lihkg.com/assets/faces/pig/read.gif)
https://sourceforge.net/p/supertuxkart/code/HEAD/tree/media/trunk/blender_26/

Use this instead, it requires blender 2.79, this 2.8 exporter is not yet ready ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)

**Comment by SlackySlackereon** [comment]
Thanks! I didn't use the Blender 2.6 one because some of the add-ons won't enable on Blender 2.6. Now I will try 2.79!
