### ISSUE TITLE
Blender 4.0 fail import SPM

### ISSUE THREAD

**Issue by ZAQraven** [supertuxkart/stk-blender#25]
Currently using stk-blender with commit 88ff5df.

```
Python: Traceback (most recent call last):
  File "/home/zaqraven/.config/blender/4.0/scripts/addons/io_scene_spm/__init__.py", line 62, in execute
    import_spm.loadSPM(context, **keywords)
  File "/home/zaqraven/.config/blender/4.0/scripts/addons/io_scene_spm/import_spm.py", line 260, in loadSPM
    material = create_material(tex_fname_1, tex_fname_2, tex_name_1, tex_name_2)
  File "/home/zaqraven/.config/blender/4.0/scripts/addons/io_scene_spm/import_spm.py", line 40, in create_material
    principled_node.inputs["Specular"].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'

```

**Comment by eijinugraha** [comment]
Maybe because not supported on blender 4.0

**Comment by eijinugraha** [comment]
i just happen like that

**Comment by ZAQraven** [comment]
Blender 3.6 and beyond can't be opened or appended with the lower Blender version. I would suggest that you fix this to keep forward.

**Comment by ZAQraven** [comment]
```
File "/home/zaqraven/.config/blender/4.0/scripts/addons/io_scene_spm/import_spm.py", line 40, in create_material
    principled_node.inputs["Specular"].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
```
As the release notes of Blender 4.0 was written:
>Specular reflection and transmission are now primarily controlled by a single index of refraction input. For texturing, a new IOR Level input adjusts the amount of specular reflection. For artistic purposes, specular tint be can set to an arbitrary color.

To avoid import failure, change 'Specular' to 'Metallic' in line 40.
