### ISSUE TITLE
We should have a button on top to export to stk

### ISSUE THREAD

**Issue by samuncle** [supertuxkart/stk-blender#5]
Currently when doing quick iteration we need to constantly switch back and forth from Scene data to some other menu we were working on just to export the scene.

![image](https://user-images.githubusercontent.com/6406045/107582586-01230380-6bfa-11eb-9c96-457628def740.png)

Moving it to the top allows to export at any time without disrupting workflow

**Comment by anon437** [comment]
This issue can be closed due to PR #13
